// Mock data store for Beagvs marketplace
import { Listing, Order, EscrowStatus, NewsArticle } from './database-types';

export const mockListings: Listing[] = [
  {
    id: '1',
    sellerId: 'seller_1',
    title: 'Premium Wireless Headphones',
    description: 'High-quality noise-cancelling wireless headphones with 30-hour battery life. Perfect for music lovers and professionals.',
    type: 'goods',
    category: 'Electronics',
    priceInPi: 25.5,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: true,
    deliveryMethods: ['courier', 'local'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    sellerId: 'seller_2',
    title: 'Professional Web Design Service',
    description: 'Custom website design and development tailored to your business needs. Responsive, modern, and SEO-friendly.',
    type: 'services',
    category: 'Digital Services',
    priceInPi: 150.0,
    images: ['https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: true,
    deliveryMethods: ['digital'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    sellerId: 'seller_3',
    title: 'Vintage Leather Backpack',
    description: 'Handcrafted genuine leather backpack with multiple compartments. Durable, stylish and perfect for daily use.',
    type: 'goods',
    category: 'Fashion',
    priceInPi: 45.0,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: false,
    deliveryMethods: ['courier', 'freight'],
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '4',
    sellerId: 'seller_1',
    title: 'Smart Home Security Camera',
    description: '1080p HD security camera with night vision and motion detection. Keep your home safe around the clock.',
    type: 'goods',
    category: 'Electronics',
    priceInPi: 35.0,
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: false,
    deliveryMethods: ['courier'],
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '5',
    sellerId: 'seller_4',
    title: 'Digital Marketing Consultation',
    description: 'One-on-one consultation to optimize your digital marketing strategy. Grow your brand and increase conversions.',
    type: 'services',
    category: 'Business Services',
    priceInPi: 75.0,
    images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: false,
    deliveryMethods: ['digital'],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '6',
    sellerId: 'seller_2',
    title: 'Organic Coffee Beans - 1kg',
    description: 'Premium organic coffee beans sourced from sustainable farms. Rich aroma, full-bodied flavor.',
    type: 'goods',
    category: 'Food & Beverage',
    priceInPi: 15.5,
    images: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&h=400&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: true,
    deliveryMethods: ['local', 'courier'],
    createdAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: '7',
    sellerId: 'seller_5',
    title: 'Modern Downtown Apartment',
    description: 'Beautiful 2-bedroom apartment in the heart of the city with stunning views.',
    type: 'real_estate',
    category: 'Apartments',
    priceInPi: 50000.0,
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: true,
    deliveryMethods: ['local'],
    propertyType: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    location: 'Downtown, City Center',
    yearBuilt: 2020,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '8',
    sellerId: 'seller_6',
    title: 'Luxury Beach House',
    description: 'Stunning oceanfront property with private beach access and panoramic views.',
    type: 'real_estate',
    category: 'Houses',
    priceInPi: 150000.0,
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: true,
    deliveryMethods: ['local'],
    propertyType: 'House',
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 3500,
    location: 'Coastal Avenue, Beach District',
    yearBuilt: 2018,
    createdAt: new Date('2024-01-29'),
    updatedAt: new Date('2024-01-29'),
  },
  {
    id: '9',
    sellerId: 'seller_7',
    title: 'Commercial Office Space',
    description: 'Prime commercial office space in business district, perfect for startups and growing businesses.',
    type: 'real_estate',
    category: 'Commercial',
    priceInPi: 80000.0,
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'],
    likes: [],
    status: 'active',
    isFeatured: false,
    deliveryMethods: ['local'],
    propertyType: 'Commercial',
    squareFeet: 2500,
    location: 'Business District, Main Street',
    yearBuilt: 2019,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
];

export const mockNews: any[] = [
  {
    id: '1',
    title: 'Beagvs Launches Global Escrow Payment System',
    slug: 'beagvs-launches-global-escrow',
    excerpt: 'We are excited to announce the launch of our new global escrow payment system, making transactions safer and more secure for buyers and sellers worldwide.',
    content: 'Full article content here...',
    author: 'Beagvs Team',
    category: 'Platform Updates',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=400&fit=crop',
    publishedAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '2',
    title: 'Real Estate Listings Now Available on Beagvs',
    slug: 'real-estate-listings-available',
    excerpt: 'Discover properties, land, and commercial spaces on Beagvs marketplace. Buy, sell, or lease real estate with cryptocurrency payments.',
    content: 'Full article content here...',
    author: 'Sarah Johnson',
    category: 'Features',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=400&fit=crop',
    publishedAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: '3',
    title: 'Earn Pi: Complete Tasks and Get Rewarded',
    slug: 'earn-pi-tasks-rewards',
    excerpt: 'Introducing our new Earn Pi feature where users can complete simple tasks for brands and earn cryptocurrency rewards.',
    content: 'Full article content here...',
    author: 'Mike Chen',
    category: 'Announcements',
    image: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=800&h=400&fit=crop',
    publishedAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: '4',
    title: 'Shipping Integration: Track Your Orders Globally',
    slug: 'shipping-integration-tracking',
    excerpt: 'New shipping tracking feature allows buyers to monitor their purchases from warehouse to doorstep with real-time updates.',
    content: 'Full article content here...',
    author: 'Emily Rodriguez',
    category: 'Platform Updates',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=400&fit=crop',
    publishedAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '5',
    title: 'Community Spotlight: Top Sellers of the Month',
    slug: 'community-spotlight-top-sellers',
    excerpt: 'Meet our top-performing sellers who are making waves in the Beagvs marketplace and learn their success strategies.',
    content: 'Full article content here...',
    author: 'David Park',
    category: 'Community',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    publishedAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order_1',
    buyerId: 'buyer_1',
    sellerId: 'seller_1',
    listingId: '1',
    totalPi: 25.5,
    deliveryMethod: 'courier',
    shippingAddress: '123 Main St, City, Country',
    trackingNumber: 'TR123456789',
    escrowId: 'escrow_1',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'order_2',
    buyerId: 'buyer_2',
    sellerId: 'seller_2',
    listingId: '2',
    totalPi: 150.0,
    deliveryMethod: 'digital',
    shippingAddress: 'digital@email.com',
    escrowId: 'escrow_2',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'order_3',
    buyerId: 'buyer_3',
    sellerId: 'seller_3',
    listingId: '3',
    totalPi: 45.0,
    deliveryMethod: 'local',
    shippingAddress: '456 Oak Ave, Town, Country',
    escrowId: 'escrow_3',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockEscrows = [
  {
    id: 'escrow_1',
    orderId: 'order_1',
    amountPi: 25.5,
    status: 'held' as EscrowStatus,
    piTransactionId: 'pi_tx_abc123',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'escrow_2',
    orderId: 'order_2',
    amountPi: 150.0,
    status: 'held' as EscrowStatus,
    piTransactionId: 'pi_tx_def456',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'escrow_3',
    orderId: 'order_3',
    amountPi: 45.0,
    status: 'released' as EscrowStatus,
    piTransactionId: 'pi_tx_ghi789',
    createdAt: new Date('2024-01-20'),
    releasedAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
];

export const mockDisputes = [
  {
    id: 'dispute_1',
    orderId: 'order_1',
    initiatorId: 'buyer_1',
    reason: 'Item not as described',
    status: 'open' as any,
    createdAt: new Date('2024-01-25'),
  },
];

export const getListingsByCategory = (category: string) => {
  return mockListings.filter(listing => listing.category === category);
};

export const getFeaturedListings = () => {
  return mockListings.filter(listing => listing.isFeatured);
};

export const getListingById = (id: string) => {
  return mockListings.find(listing => listing.id === id);
};

export const getOrderById = (id: string) => {
  return mockOrders.find(order => order.id === id);
};

export const getEscrowByOrderId = (orderId: string) => {
  return mockEscrows.find(escrow => escrow.orderId === orderId);
};
